### ISSUE TITLE
create a PDFGenerationApi

### ISSUE THREAD

**Issue by lynncyrin** [project-callisto/callisto-core#150]

**Comment by lynnco** [comment]
spawned from https://github.com/SexualHealthInnovations/callisto-core/issues/147

**Comment by lynnco** [comment]
I'm going to have to add a temporary test skip to https://github.com/SexualHealthInnovations/callisto-core/pull/149, to be removed with this issue is resolved

**Comment by kelseyq** [comment]
I'm not sure I'm for this. If you wanted to do an implementation that used PDF generation but didn't use email notifications (for example, one based on SFTP delivery) you'd still have to depend on the notifications app and as a result you'd end up with an unused db table for EmailNotification

**Comment by lynnco** [comment]
That's a good point and strong argument against pairing PDF generation and email notification more thoroughly.

I do still think PDF generation should be a bit more separate from the delivery app, but yea I agree that moving it into notification is probably not the way to accomplish that

**Comment by kelseyq** [comment]
i have an idea on separating them out a bit more, will elaborate in #149

**Comment by lynnco** [comment]
was decided in #149 that a better option is creating a PDFGenerationApi
