### ISSUE TITLE
check Twitter and Facebook match identifiers against allowed characters in those usernames

### ISSUE THREAD

**Issue by kelseyq** [project-callisto/callisto-core#181]
right now, we just check if a Twitter handle is less than 15 characters and don't impose any checks on the FB URL.

slight complication: we accept Facebook URLs in the old style (/profile.php?id=XXXXXXXXXX) as well as custom URLs

**Comment by lynnco** [comment]
I think the most accurate / sustainable long term method of username validation would be using twitter's API (either http, js, or python) to validate the usernames, pulling their ID (which is unique on the site, and doesn't have an option to be changed), and appending the social url.

so like `12312415123@twitter.com`

and a similar thing with facebook

**Comment by lynnco** [comment]
but I think there's also another unanswered question here about how matching should be designed. ie 

- do you want the match criteria to have strict validation? no validation?
- are social urls the best option?
- would using google's api for determining matches be an overreach? 

These are, I think, not small questions. I might require a team of people with specific domain knowledge to answer them >_<

**Comment by kelseyq** [comment]
> I think the most accurate / sustainable long term method of username validation would be using twitter's API (either http, js, or python) to validate the usernames

this is 100% a no-go; we will not be sending information about accused perpetrators to Twitter under any circumstances

**Comment by lynnco** [comment]
phewwwwwww yea good call, I didn't think about that
