### ISSUE TITLE
When multiple checkboxes are selected in callisto report, the answer is not reflected in report review

### ISSUE THREAD

**Issue by scattermagic** [project-callisto/callisto-core#306]
When a selected a single checkbox in a report, the answer is properly reflected in the report review page. When more than one checkbox is selected, the report review displays:
[ Not Answered ]

**Comment by lynncyrin** [comment]
I haven't noticed this particular issue before, I'll write a test case for it later today

**Comment by lynncyrin** [comment]
Confirmed https://github.com/project-callisto/django-wizard-builder/pull/187
