### ISSUE TITLE
Unable to use multiple passphrases

### ISSUE THREAD

**Issue by scattermagic** [project-callisto/callisto-core#307]
When entering a passphrase to access a file, that password is then used to access other documents. 

If you make 2 reports with different passphrases, 
and you access 1 with its passphrase, 
if you then try to access the other you will get a decrypt error because it will try to use the passphrase from the first report to decrypt the second.

**Comment by lynncyrin** [comment]
Confirmed, this one is also on my radar for the next few weeks

**Comment by lynncyrin** [comment]
@scattermagic this should be fixed with `v0.16.0` and https://github.com/project-callisto/callisto-core/pull/313, feel free to re-open if its not!
