### ISSUE TITLE
demo site login fails

### ISSUE THREAD

**Issue by compwron** [project-callisto/callisto-core#361]
Logging into the demo site at https://callisto-core.herokuapp.com/# with demo/demo as instructed does not succeed (screenshot) 
<img width="1055" alt="screen shot 2017-12-28 at 10 37 52 am" src="https://user-images.githubusercontent.com/578159/34419907-4c8aec10-ebbb-11e7-993a-642103fbf8fd.png">

**Comment by lynncyrin** [comment]
Confirmed! The demo app is getting its login backend changed in https://github.com/project-callisto/callisto-core/pull/346

**Comment by drnikki** [comment]
Is there a way I can look at the demo site while 346 is in progress?

**Comment by lynncyrin** [comment]
Its back up! https://callisto-core.herokuapp.com/ Sorry I left this one on the backlog for so long!

// @drnikki @compwron
